POST localhost:8082/sol
Content-Type: application/json
Accept: application/json

{"sol":  23,
"fullName": "Neha Narkhede"}

###
POST localhost:8082/sol
Content-Type: application/json
Accept: application/json

{"sol":  23,
  "fullName": "Jay Kreps"}
